### ISSUE TITLE
Form 8949 uses column g for cost basis adjustment instead of just entering the correct amount in column e

### ISSUE THREAD

**Issue by davewalter** [hickeng/financial#100]
First of all, thank you so much for all of your effort into producing such a comprehensive spreadsheet that has (mostly) taken the anxiety out of filing taxes this year.

One thing that I noticed while working through the sheet over the weekend was that the RSU section with the entries for IRS form 8949 doesn’t seem to exactly follow the [IRS instructions](https://www.irs.gov/instructions/i8949#en_US_2022_publink59421zd0e1936). Specifically, the instructions state:

> IF . . .
> You received a Form 1099-B (or substitute statement) and the basis shown in box 1e is incorrect
> 
> THEN enter this code in column (f) . . .
> B
> 
> AND. . .
> If this transaction is reported on a Part I with box B checked at the top or if this transaction is reported on a Part II with box E checked at the top, enter the correct basis in column (e), and enter -0- in column (g).

Using column g for the adjustment does result in the same gain/loss, so it’s a very minor change, but a question came up in Slack today so I suspect that others are going to start running into the same thing soon.

I would PR a fix in myself, but I think that would cause you more headaches than just raising an issue and letting you fix it yourself. Please let me know if this is not the case and I will happy make the change for you.

**Comment by hickeng** [comment]
Thanks Dave - I saw this having just come to open an issue for this exact point.

I'll make the fix, but I'll also need to go through another TurboTax run to figure out what it does to the entry flow. We still need TT to generate the `B` code and I'm not sure it does that if you don't hit "the basis is incorrect" radio button.

I'll update the sheet regardless for correctness, but prefer to do the doc update at the same time if one is needed.

**Comment by garyrussell** [comment]
@hickeng I can confirm that TT adds the `B` code (and puts the modified basis in column (e)), but just for those where the cash was greater than the total gain; when the correct basis is zero, no `B` is added - as one might expect.

**Comment by hickeng** [comment]
@garyrussell don't know if this is what you meant, but even if you've entered the value as an adjustment instead of as basis, TT does the correct thing with it in terms of placing the adjustment into (e) as the basis for RSUs.

**Comment by garyrussell** [comment]
Yes, sorry for the confusion; as I mentioned in slack, it just looked wrong to me to change column (d) to include the stock value.

**Comment by garyrussell** [comment]
![Screenshot 2024-03-18 at 3 14 42 PM](https://github.com/hickeng/financial/assets/483832/cafe609f-4658-4c4e-93f5-6b8986c5d2f8)
![Screenshot 2024-03-18 at 3 18 54 PM](https://github.com/hickeng/financial/assets/483832/92f1944a-96e5-4c90-9c6b-85a282319225)



@hickeng I am seeing these errors on the v0.16 reference sheet.

Also, when I set E9 to `cashOnly`, I see the AVGO FMV removed from the proceeds (d), but not from the basis (e); I expected the basis to be `cashReceived - totalValue` (when total value is less than cash received).

**Comment by hickeng** [comment]
@garyrussell The Probably Fraction Threshold is a work-in-progress field for trying to automate the fractional lot selection. I'd expect to see a value there only if you've got values in the `AVGO qty from eTrade` column as it's calculating a stddiv across the ratio for those entries.

The `Form 8949 proceeds` is similar - it's a work-in-progress toggle for switching the Form8949 behaviour. It's not exposed via a dropdown in the Summary page because I haven't finished it yet. See #98 .

I am surprised that `Balance share ratio` is showing a `#Name?` error - is that Excel and not Google Sheets? If so, then you need to adjust some lines in that formula from `error("insufficient balance lots")` to just the text string. `error` is a non-existent function that was using to flag an error. It works in Sheets as it doesn't appear to evaluate all terms ahead of time, but Excel does.

**Comment by garyrussell** [comment]
Sorry, I didn’t realize this was WIP because this issue is closed.

This error is in Google Sheets, I just used the `File -> Make a new copy` option.
