### ISSUE TITLE
Binary version of 0.1.6 is missing

### ISSUE THREAD

**Issue by sreenivasmrpivot** [hickeng/financial#116]
Binary version of 0.1.6 is missing, can you kindly upload it and update the link in install.md please?

**Comment by hickeng** [comment]
The binaries for a specific release are linked from the release page. For v0.1.6, see: https://github.com/hickeng/financial/releases/tag/v0.1.6

[install.md](https://github.com/hickeng/financial/blob/main/install.md) HEAD has links to the latest binaries, currently v0.1.6-b. There were two cross-row skew references introduced during making the formula more human readable which I fixed in-place in the shared sheets asap and with the v0.1.6-b binary attachment.

It's not good release hygine, but given the access patterns it makes sense to do it this way to minimize peoples exposure to the errors.

I suspect you must be browsing the repo at the v0.1.6 tag, hence install.md having links to the removed v0.1.6 binaries.
