### ISSUE TITLE
change date fields to a format more obvious of dd-mon-year. for example to make 2023-dec-01

### ISSUE THREAD

**Issue by a1ch3mist** [hickeng/financial#129]
I was entering dates in as m/d/yr (e.g. 12/1/2023) and google took that to mean Jan 12, 2023. I didn't catch this until later.

To avoid date issues, change the format to spell the month dd-MON-yyyy something like that to prevent any issues

**Comment by hickeng** [comment]
Good suggestion - textual month and 4 digit year seems the only way to make this properly unambiguous.

It's just as problematic in the Excel version although that simply ends up converting some date values to pure text because month 13 doesn't exist... and your only indication is difference in text alignment.

**Comment by hickeng** [comment]
I've updated the shared sheets with the format change (did so on Monday). Still need to apply the change to the sheets in the repo.
