### ISSUE TITLE
What's the significance of the 8937 distribution forms?

### ISSUE THREAD

**Issue by shashankram** [hickeng/financial#143]
Does the sheet consider these forms as inputs for the calculations, or do the 8937 forms need to be used to augment the outputs from the sheet?

Thanks

**Comment by hickeng** [comment]
They are reference materials that were used to construct the sheet.

The three 8937's for Dell Distributions detail the two special dividends and how that adjusted the basis of any VMW shares held over those ex-dividend dates. There's three forms for two events because eTrade used the estimated value from the draft form for the 2021 dividend.

There's a single 8937 that governs the tax impact for shareholders of the Broadcom/VMware merger that details the bulk of the calculations needed in the sheet.

The rest of the calculations in the sheet are pulled from various sources and links to those are generally provided in the Reference section of the readme, or the corresponding issues.

**Comment by shashankram** [comment]
I am still not sure how these forms are to be utilized for filing taxes. Aside from the output the sheet generates, how is this to be used by the CPA?

**Comment by hickeng** [comment]
The forms are reference material. They describe the specific impact of dividends and merger on the vmw shares and were filed by VMware and Broadcom at the time of the dividends and merger.

A CPA may already know all of these details, but if they don't, those are the forms they'll need to reference.

To be clear, Form 8937 is not something you need to fill in, or even know about unless you want to understand the details of the tax calc.

The only Form you must care about is 8949 that's filed by individuals with the IRS. The sheet generates the numbers for 8949, labelled as such.

If using TurboTax or similar, it will generate a Form8949 for you, using imported 1099B from Etrade. In that case you use the 8949 numbers from the sheet to correct the 1099B data after TT has imported it.

If using a CPA, you can copy the three Form8949 sections from the sheet and provide them with those numbers. Ask your CPA if they want the combined cash+shares Proceeds or the cash only, and set the Summary dropdown for 8949 Display style based on their answer.
