### ISSUE TITLE
Incorrect calcuation for RSU and ESPP lot

### ISSUE THREAD

**Issue by winkingturtle-vmw** [hickeng/financial#87]
While looking over latest version (0.1.4) of this sheet, I noticed that the lot calculation is not correctly represented.

For example, if anyone had any RSU on 09/01/23 at price of $164.10, Form 8949 should show a loss and not gain since it was sold at $142.50. Does this make sense or is there something here that I missed?

**Comment by hickeng** [comment]
I've added some [doc here](https://github.com/hickeng/financial/blob/main/usage.md) to explain.

Unless you took all cash, you cannot realize a loss on the merger. I've an issue open to clarify whether this statement applies only overall or on a per-lot basis, see #66 

TLDR; you didn't take a loss because you also got shares. For lots where the VMW basis is higher than the AVGO FMV you get to defer tax into the future via the alternate gain calculation in form8937.
