### ISSUE TITLE
"cashOnly" setting for Form8949 Proceeds does not work

### ISSUE THREAD

**Issue by chidov** [hickeng/financial#98]
In reference sheet, a field name "Form8949 proceeds" has an error which default to "combined", and when I manually change to "cashOnly", it shows adjustment (g) in RSU sheet is more than proceed (d) which is the same amount of adjustment (g) when we select combined.

**Comment by hickeng** [comment]
I've not yet implemented a toggle for using cash only in the f8949 fields. The unknown ref is because I took out a dropdown that would allow switching the behaviour given it wasn't fully plumbed through.

I may or may not get to this, depending on how many people want to report using that style. Personally I prefer the combined style, reasoning noted [here](https://github.com/hickeng/financial/blob/main/usage.md#form-8949).
