### ISSUE TITLE
LT Capital Gain in ESPP tab should exclude Ordinary Income?

### ISSUE THREAD

**Issue by inin2626** [hickeng/financial#99]
In the ESPP tab, column BB (Long Term Capital Gain) is equal to column AX (Potential Capital Gain-AVGO). But there is also Ordinary Income which is the 15% of VMW Grant date market value. Shouldn't the Long Term Capital Gain be post-adjustment of Ordinary Income? i.e. Capital Gain = Sales - Cost Basis - Adjustment for Ordinary Income.  It seems to me that the column BB is overstated by the amount of Ordinary Income. I'm not an expert; I tried to model it out, and currently the calculations don't tie out because of this discrepancy.

**Comment by hickeng** [comment]
Yeah, these columns were a rough approximation. I've made changes to this to properly reflect the actual pending gain, specifically because it's needed by people using the `Post merger sale of AVGO` tweak to figure out impact from selling post-merger in 2023.

My WIP v0.1.6 breaks out the ESPP basis into two columns:
* pure basis with adjustment for return's of capital and the recognized merger gain - this is probably what you'd need if instructing a broker to update basis in their backend systems
* basis to be used when selling, which includes the Ordinary Income portion

These changes relate to your question in that, yes the LTG should be presented after the imputed income has been accounted for... but per IRS guidance that's done via a basis adjustment not via a direct deduction.

See #15

**Comment by hickeng** [comment]
This was fixed in 912a33737a0692668db730a6267bdc6633303271 - I was naughty twice. I combined a formula change with the beautification pass, and then forgot to note that it fixes this issue in the commit message.
